### ISSUE TITLE
Import chat to a group

### ISSUE THREAD

**Issue by MuhammadArifAbdulMalek** [filippz/telegram_import#9]
Is there a way to import the chat to a private group? If possible, how is it supposed to be done differently? 

I am getting this error using the group link

telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: IMPORT_PEER_TYPE_INVALID (caused by InitHistoryImportRequest)

**Comment by filippz** [comment]
AFAIK, the `group` must be `supergroup` - as there is no more "Convert to `supergroup`" option within client apps (at least Android and Windows), the easiest way to convert `group` to `supergroup` is to convert it to `Public` (which also converts the `group` to `supergroup`) and revert it back to `Private` (but the group remains `supergroup`).

Recent disccusion about the problem is here: https://github.com/filippz/telegram_import/issues/5
